name: Playwright Tests
name: Playwright Tests

on:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    

    	

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build project
        run: mvn clean install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run test
        run: mvn exec:java -Dexec.mainClass=tests.LoginTest
