name: Run Playwright Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install
        
        - name: Setup Node
  		uses: actions/setup-node@v4
  		with:
    		node-version: '18'
        

     - name: Install Playwright browsers
        run: npx playwright install


      - name: Run test
        run: mvn exec:java -Dexec.mainClass=tests.LoginTest
